### ISSUE TITLE
Agrégation de pack

### ISSUE THREAD

**Issue by malexxx** [jersou/studio-pack-generator#1]
Salut,
Félicitations pour cet outils qui devient un musthave pour tout luniiste !

Ce qu'il nous manque aujourd'hui reste la fusion de 2 packs existants.
A la lecture de ton code, cette fonction semble réalisable facilement ?

**Comment by jersou** [comment]
Salut, merci :-)

Oui, j'y pensais hier justement, j'imagine pour ma même raison que toi : la discussion sur Deallabs qui parle de place sur la Lunii et que c'est difficile de naviguer dedans s'il y a trop de pack.

Je me suis noté l'idée de faire la conversion dans l'autre sens zip → dossier de fichiers structuré (tel que l'attend studio-pack)
Dans l'idée de pouvoir faire un dossier qui contient d'autre dossier de pack et faire un gros pack qui en agrège d'autres...

Mais en lisant ta question, je me dis qu'il n'est même pas nécessaire de passer par la version "fichier" du pack, on pourrait garder le zip et studio pack pourrait lire le pack et copier/coller en qq sorte.

Je vais y réfléchir dès que j'ai un peu de temps.

**Comment by jersou** [comment]
La possibilité de fusionner plusieurs packs vient d'être ajouté, elle est dispo dans la v0.1.11.
Pour fusionner des pack, il suffit d'ajouter le(s) zip au format Studio dans l'arbo de fichier, comme décit là : https://github.com/jersou/studio-pack-generator#zip-pack-aggregation

**Comment by malexxx** [comment]
Merci d'avoir intégré cette amélioration. 
Je teste asap

**Comment by kpouget** [comment]
>  Félicitations pour cet outils qui devient un musthave pour tout luniiste !

je squate le ticket pour ajouter un +100 à ça, j'utilisais https://github.com/marian-m12l/studio depuis longtemps, mais les GUIs c'est bien un moment, mais quand les histoires deviennt trop complexes ... il n'y a plus assez de places pour ranger ses nodes 🙃

donc super cette version dossier + CLI, ma mère peut même générer ses structures d'histoires et je n'ai qu'à transformer-uploader 🎆

**Comment by jersou** [comment]
> > Félicitations pour cet outils qui devient un musthave pour tout luniiste !
> 
> je squate le ticket pour ajouter un +100 à ça, j'utilisais https://github.com/marian-m12l/studio depuis longtemps, mais les GUIs c'est bien un moment, mais quand les histoires deviennt trop complexes ... il n'y a plus assez de places pour ranger ses nodes upside_down_face
> 
> donc super cette version dossier + CLI, ma mère peut même générer ses structures d'histoires et je n'ai qu'à transformer-uploader fireworks

Merci pour ce retour ! Ça fait plaisir :-)
