### ISSUE TITLE
Studio failed to read Merged pack with SPG

### ISSUE THREAD

**Issue by malexxx** [jersou/studio-pack-generator#10]
tested with some differents packs, always the same error.

Here I try to merge
3+]Marlène Jobert raconte (05 histoires)[by_ipeca.zip
3+]Marlène Jobert raconte (06 histoires) [by_Tupid.zip

log from SPG
`studio-pack-generator-x86_64-windows.exe test
{ deno: "1.18.2", v8: "9.8.177.6", typescript: "4.5.2" }
{
  opt: { [...]  }
}
create test-1644657400474.zip
add to zip : assets/
add to zip : assets/8a7e90fb654dd87957b81f23570a1a2ba6355b87.mp3
[...]
add to zip : assets/97d6658c931888ae154d43b67a5186047908d529.mp3
add asset 0-item.png
add asset 0-item.mp3
add asset choisir un pack\0-item.mp3
add asset choisir un pack\0-item.png
write test-1644657400474.zip
Done (26.159 sec) :  test → test-1644657400474.zip`

Error from studio : 
`2022-02-12 10:11:51,630 [ERROR] [s.w.s.LibraryService]: Failed to read archive-format pack C:\Users\[user]\Desktop\STUDIO~1.1VT\.studio\library\test-1644657400474.zip from local library`

**Comment by malexxx** [comment]
Directory :
C:\Users\[user]\Desktop\Studio-Pack-Generator>dir test /s /b
C:\Users\[user]\Desktop\Studio-Pack-Generator\test\choisir un pack
C:\Users\[user]\Desktop\Studio-Pack-Generator\test\choisir un pack\3+]Marlène Jobert raconte (05 histoires)[by_ipeca.zip
C:\Users\[user]\Desktop\Studio-Pack-Generator\test\choisir un pack\3+]Marlène Jobert raconte (06 histoires) [by_Tupid.zip

**Comment by jersou** [comment]
Fixed. The fix will be in v0.1.18.
Waiting for this version, here are 2 workarounds:
- unzip and zip the pack
- import the pack from Studio Editor
