### ISSUE TITLE
Use thumbnail from rss feed for generating item.png

### ISSUE THREAD

**Issue by malexxx** [jersou/studio-pack-generator#11]
Lot of RSS got image in rss.
Can you use this meta instead generate them on filename ?

De nombreux RSS contiennent une image dans leur flux RSS
Peux tu utiliser cette métadonnée plutôt que la générer depuis son nom de fichier ?

Merci d'avance.

**Comment by jersou** [comment]
Salut ! c'est déjà le cas cf https://github.com/jersou/studio-pack-generator/blob/main/generate/rss_parser.ts#L56
mais j'imagine que ça ne suffit pas, je me suis basé sur quelques exemples de flux, mais j'imagine que ça ne fonctionne pas avec tous. Je n'ai pas vérifié s'il y avait une spec pour les flux RSS.
Tu as un exemple de flux avec lequel l'extraction d'image ne fonctionne pas ?

**Comment by arnaudruffin** [comment]
Voici un exemple: https://feeds.acast.com/public/shows/petit-vulgaire

J'ai l'impression que la balise "itunes:image" peut certaines fois faire l'affaire....

**Comment by jersou** [comment]
La dernière release a ajouté cette fonctionnalité, elle peut être désactiver si besoin avec `--skip-rss-image-dl`
