### ISSUE TITLE
Have an option to disable autoplay on the Stage Node

### ISSUE THREAD

**Issue by Dllieu** [jersou/studio-pack-generator#12]
Currently, when generating a package and loading it with STUdio, all the stage nodes are set to autoplay:
```Enable AUTOPLAY: whether the Story Teller should automatically play the OK transition when the audio file is done playing (you may want to enable this when playing a question or a story)```

Having an option to disable autoplay would be a great addition

**Comment by jersou** [comment]
I don't really understand what you would like?

Do you follow this file structure?
```shell
📂 Story folder
└── 📂 Choose a character          ← 📂 first menu
    ├── 📂 Alice                     ← 📂 first choice of the first menu
    │   └── 📂 Choose a place          ← 📂 second menu
    │       ├── 🎵 the city.mp3          ← 📗 audio story
    │       └── 🎵 the jungle.mp3        ← 📗 audio story
    └── 📂 Bob                       ← 📂 second choice of the first menu
        └── 📂 Choose a place          ← 📂 second menu
            ├── 🎵 the desert.mp3        ← 📗 audio story
            └── 🎵 the jungle.mp3        ← 📗 audio story
```
It's for the stories maybe? You would like to disable the automatic return to the parent menu at the right ? 
![ex-full](https://user-images.githubusercontent.com/5874319/155212558-bb982a5e-2260-4fc3-9389-f346be218c10.png)
