### ISSUE TITLE
Problème TTS windows 11

### ISSUE THREAD

**Issue by resom78** [jersou/studio-pack-generator#13]
Sous windows 11 les fichiers de titres en mp3 ne sont pas générés. 
Y a t'il un paramétrage à faire pour faire fonctionner le TTS sous windows 11?

**Comment by schmurtzm** [comment]
I think it's not related to Windows 11 , see this issue :  https://github.com/jersou/studio-pack-generator/issues/14

**Comment by jersou** [comment]
vous utilisez bien la release zeip dispo ici  https://github.com/jersou/studio-pack-generator/releases/download/v0.1.17/studio-pack-generator-x86_64-windows.zip ?

**Comment by jersou** [comment]
Je suppose que c'est à cause de ça, je ferme le ticket, commentez ici si ce n'est pas le cas
