### ISSUE TITLE
menu audio files : problem with TTS generation on Windows (WSL instead Windows TTS)

### ISSUE THREAD

**Issue by schmurtzm** [jersou/studio-pack-generator#14]
Hello,

when generating a pack on Windows 10 with studio-pack-generator v0.1.17 I see this command line : 
"C:\WINDOWS\system32\wsl.exe" pico2wave -l fr-FR -w "/mnt/g/Studio-Pack-Generator/test/Ourson.item.wav" " . Ourson . "

But theoretically wsl is not a required dependency : "Windows release use Windows TTS instead of picoTTS"

This is annoying to doesn't have audio on each title because without it Studio refuse to convert a pack.

Thank you !

**Comment by MrAlucardDante** [comment]
I can confirm that the issue is real, although the project hasn't been updated in a year.

Maybe someone will fork it to fix that

**Comment by jersou** [comment]
**Feel free to fork this project or to submit a PR !**

I did not reproduce this bug at the time on my Windows VM...

Do you use the release for Windows here  https://github.com/jersou/studio-pack-generator/releases/download/v0.1.17/studio-pack-generator-x86_64-windows.zip ?
or with deno directly ?

@schmurtzm :
> But theoretically wsl is not a required dependency : "Windows release use Windows TTS instead of picoTTS"

→ yes ! the zip release, from https://github.com/jersou/studio-pack-generator/releases/

Another doc in french here : https://github.com/jersou/studio-pack-generator/wiki/Tuto-Windows-FR

The Readme should be updated to specify that it is necessary to use the zip release or to have WSL installed to have the TTS...

Anyway, there is probably a bug in the detection of WSL and Pico2Wave.

**Comment by MrAlucardDante** [comment]
Here are the logs, hope this helps : 
`
PS C:\Studio-Pack-Generator> .\studio-pack-generator-x86_64-windows.exe "pack"
{ deno: "1.18.2", v8: "9.8.177.6", typescript: "4.5.2" }
{
  opt: {
    _: [],
    "skip-image-item-gen": false,
    i: false,
    skipImageItemGen: false,
    "skip-audio-item-gen": false,
    a: false,
    skipAudioItemGen: false,
    "skip-audio-convert": false,
    v: false,
    skipAudioConvert: false,
    "skip-extract-image-from-mp3": false,
    m: false,
    skipExtractImageFromMp3: false,
    "skip-zip-generation": false,
    z: false,
    skipZipGeneration: false,
    "skip-not-rss": false,
    s: false,
    skipNotRss: false,
    "auto-next-story-transition": false,
    n: false,
    autoNextStoryTransition: false,
    "add-delay": false,
    d: false,
    addDelay: false,
    "night-mode": false,
    t: false,
    nightMode: false,
    "seek-story": undefined,
    c: undefined,
    seekStory: undefined,
    "$0": "deno run",
    "story-path": "pack",
    storyPath: "pack"
  }
}
Try convert pack\test pack\story.mp3 → pack\test pack\story.item.png
checkCommand [ "C:\\Studio-Pack-Generator\\tools\\ffmpeg.exe", "-version" ]
→ KO :
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mp3, from 'pack\test pack\story.mp3':
  Metadata:
    artist          : Zouk (2021)
    title           : Mister Ogre
    comment         : fre:ac - free audio converter <https://www.freac.org/>
    encoder         : fre:ac v1.1.6
  Duration: 00:11:05.21, start: 0.025057, bitrate: 163 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 163 kb/s
    Metadata:
      encoder         : LAME3.100
Output #0, image2, to 'pack\test pack\story.item.png':
Output file #0 does not contain any stream

Generate image to pack/0-item.png
checkCommand [ "C:\\Studio-Pack-Generator\\tools\\convert.exe", "--version" ]
convert.exe: UnableToOpenConfigureFile `colors.xml' @ warning/configure.c/GetConfigureOptions/705.
Generate audio to pack/0-item.wav
checkCommand [ "wsl", "pico2wave", "--version" ]
checkCommand [ "wsl", "pico2wave", "--version" ]
Une erreur s’est produite lors du montage de l’un de vos systèmes de fichiers. Veuillez exécuter la commande « dmesg » pour plus d’informations.
Generate audio to pack/0-night-mode.wav
Une erreur s’est produite lors du montage de l’un de vos systèmes de fichiers. Veuillez exécuter la commande « dmesg » pour plus d’informations.
Generate image to pack\test pack/0-item.png
convert.exe: UnableToOpenConfigureFile `colors.xml' @ warning/configure.c/GetConfigureOptions/705.
Generate audio to pack\test pack/0-item.wav
Une erreur s’est produite lors du montage de l’un de vos systèmes de fichiers. Veuillez exécuter la commande « dmesg » pour plus d’informations.
Generate image to pack\test pack/story.item.png
convert.exe: UnableToOpenConfigureFile `colors.xml' @ warning/configure.c/GetConfigureOptions/705.
Generate audio to pack\test pack/story.item.wav
Une erreur s’est produite lors du montage de l’un de vos systèmes de fichiers. Veuillez exécuter la commande « dmesg » pour plus d’informations.
get max volume of file pack\test pack\story.mp3
→ OK : 4.5 Db
Convert file pack\test pack\3fb09ec7.mp3 → pack\test pack\story.mp3
"C:\Studio-Pack-Generator\tools\ffmpeg.exe" "-i" "pack\test pack\3fb09ec7.mp3" "-af" "volume=4.5dB,dynaudnorm" "-ac" "1" "-ar" "44100" "-map_metadata" "-1" "-y" "pack\test pack\story.mp3"
→ OK
Try convert pack\0-item.png → pack\thumbnail.png
→ OK
create pack-1675201380802.zip
add asset test pack\story.mp3
add asset 0-item.png
add asset test pack\0-item.png
add asset test pack\story.item.png
write pack-1675201380802.zip
Done (13.81 sec) :  pack → pack-1675201380802.zip
`

**Comment by jersou** [comment]
Une option `--skip-wsl` a été ajoutée à la dernière release pour désactiver l'usage de WSL pour le TTS

**Comment by MrAlucardDante** [comment]
Merci pour ce correctif, je le testerais dès que possible demain.

En passant le lien vers Discord n'est pas bon, c'est un lien vers un salon textuel mais il ne fonctionne pas si l'on est pas déjà membre du serveur auquel il est lié.

Je ne trouve de lien vers un serveur Discord sur la page Github, il pourrait être judicieux de l'ajouter en plus du lien vers le salon

**Comment by jersou** [comment]
ok, merci pour l'info sur le lien, j'avais un doute.
> Je ne trouve de lien vers un serveur Discord sur la page Github, il pourrait être judicieux de l'ajouter en plus du lien vers le salon
je ne comprends pas du coup, le lien qui ne marche pas, c'est pas celui du Readme d'accueil ? ou tu parles du github de studio ?

le bon lien sans doute : https://discord.com/invite/jg9MjHBWQC

**Comment by MrAlucardDante** [comment]
C’est bien le lien du readme qui n’est pas bon. Merci pour le lien

**Comment by jersou** [comment]
Je n'ai pas reproduit sur un pc Windows avec wsl installé, mais pas pico2wave, même sans l'option --skip-wsl, le TTS a été généré.

Je clos le ticket, commenter ici si ce n'est résolu.
