### ISSUE TITLE
Can't launch de Windows .exe

### ISSUE THREAD

**Issue by Cuhesse** [jersou/studio-pack-generator#15]
Hi,
Thanks for the hard work!
When I try to launch the application but nothing's happen except a 0.5 second cmd prompt that stop immediately.
Do I have to install something or configure something before launching it?

Thanks in advance.

**Comment by Cuhesse** [comment]
+1

**Comment by jersou** [comment]
Hi,
I have no idea what it could be!
* You don't get any error message ?
* What version of Windows are you using? 64 bit version ?
* You have to add the path of an existing folder just after the executable, and this folder has to be in the right format.
→ https://raw.githubusercontent.com/wiki/jersou/studio-pack-generator/img/04.webp
→https://github.com/jersou/studio-pack-generator#story-folder-structure
* You use this version ? → https://github.com/jersou/studio-pack-generator/releases/download/v0.1.17/studio-pack-generator-x86_64-windows.zip
a tutorial in french (not by me, thanks iinul) : https://youtu.be/rzc8txH-jjA?t=344
