### ISSUE TITLE
Lire automatiquement la piste suivante

### ISSUE THREAD

**Issue by sferlisi** [jersou/studio-pack-generator#16]
Bonjour,
Encore un tout grand merci pour cet outil.
J'aimerais mettre des musiques sur la lunii et comme pour les histoires, je donne la possibilité à mon lulu de choisir la chanson qu'il veut écouter.
Par défaut, j'aimerais qu'une fois qu'il a choisi une chanson, la chanson suivante soit lue à moins qu'il clique sur la maison pour revenir au menu.

Je n'arrive pas à trouver comment lui dire de lire automatiquement la chanson suivante. Est-ce que quelqu'un peut m'aider ?
(Je n'ai pas trouvé non plus une documentation pour chercher je dois dire :) )

**Comment by jersou** [comment]
Bonjour,
je pense que ce que vous cherchez est l'option : 
```
  -n, --auto-next-story-transition   go to next story of group at end of stories              [boolean] [default: false]
```
Au lieu de lancer 
`studio-pack-generator ...`
il faut alors ajouter `-n` juste après le nom du programme :
`studio-pack-generator -n ...`

Avec cette option, il est toujours possible de choisir un chapitre/musique, mais à la fin de la lecture, ça passe au suivant automatiquement.
Ça ne passe automatiquement au suivant que pour un même "groupe", c'est-à-dire un même dossier.

Par exemple, pour une structure de dossiers/fichiers : 
```
📂 Story folder
└── 📂 Choose a character          ← 📂 first menu
    ├── 📂 Alice                     ← 📂 first choice of the first menu
    │   └── 📂 Choose a place          ← 📂 second menu
    │       ├── 🎵 the city.mp3          ← 📗 audio story
    │       └── 🎵 the jungle.mp3        ← 📗 audio story
    └── 📂 Bob                       ← 📂 second choice of the first menu
        └── 📂 Choose a place          ← 📂 second menu
            ├── 🎵 the desert.mp3        ← 📗 audio story
            └── 🎵 the jungle.mp3        ← 📗 audio story
```
à la fin de "the city", ça passera à "the jungle" automatiquement, mais ça s'arrêtera à la fin the jungle sans passer à la suite (ça ne passera pas sur "the desert").
