### ISSUE TITLE
Quelques ms d'audio manquant au début de chaque fichier

### ISSUE THREAD

**Issue by MrAlucardDante** [jersou/studio-pack-generator#18]
Lors de la conversion des fichiers MP3, il manque quelques millisecondes au début de chaque fichier.

Par exemple, le fichier audio dit "Choisis ton personnage", lors de la lecteur de l'histoire, on entends "si ton personnage"

**Comment by jersou** [comment]
Une option existe déjà pour ça : 
```
  -d, --add-delay                    add 1 second at the beginning and the end of audio files [boolean] [default: false]
```

**Comment by MrAlucardDante** [comment]
Le problème n'est pas que je veux ajouter un délai au début et a la fin mais que l'audio fournit en entrée n'est pas identique en sortie, puisqu'il manque quelques millisecondes.

De plus -d ajoute 1s au début ET a la fin, donc rajouter 2 secondes a un fichier qui ne fait déjà que 2 secondes ou moins pour annoncer le nom d'un personnage ou d'un lieu n'est pas idéal

**Comment by jersou** [comment]
Bizarre, je peux avoir un exemple de fichier d'entrée et de sortie ?

**Comment by MrAlucardDante** [comment]
En effet le problème est présent sur la Lunii et pas avec le fichier lui même.

Je viens de convertir un fichier MP3 avec SPG et il n'est pas tronqué.

Une fois le pack généré, je l'importe dans la version 1.x.x de STUdio maintenu par kairoh et il est possible que le problème vienne de STUdio lui même.

Je ferais un test demain pour voir si STUdio n'aime pas les fichiers convertis par SPG (peu probable) ou si il le fait avec n'importe quel fichier.

En tout cas merci pour ces informations.

**Comment by jersou** [comment]
Je ne pense pas que ça vienne de Studio, mais de la Lunii qui ne lit pas les premières ms
Pour info, il y a un ticket "Add delay before any sound" dans le projet studio : https://github.com/marian-m12l/studio/issues/25
