### ISSUE TITLE
Le bouton Home ne revient pas assez en arrière

### ISSUE THREAD

**Issue by MrAlucardDante** [jersou/studio-pack-generator#19]
C'est peut etre un choix plutot qu'un bug afin de ne pas avoir a rechoisir tout si l'on veut juste changer un élément, mais lorsque l'on appuie sur le bouton Home, nous ne revenons pas au tout premier choix mais nous restons sur noeud d'action précédent.

Les packs officiels reviennent au tout début afin de pouvoir faire de nouveaux choix.

Par ailleurs, il faut appuyer 2 fois sur le bouton Home pour revenir au noeud d'action précédent sinon nous tournons en rond.
Par exemple :
-> Nom du pack
OK
--> Choisis un personnage
---> Alice
OK
----> Ou l'histoire va-t-elle se passer ?
-----> Dans un parc
OK
------> Enfin choisis un objet
-------> Un ballon
Home
------> Enfin choisis un objet
-------> Un ballon
Home
------> Enfin choisis un objet
-------> Un ballon

A minima on devrait revenir sur le choix précédent (ici Ou l'histoire va-t-elle se passer ?) et si l'on veut simuler un vrai pack, on devrait revenir au tout début.

Ce fonctionnement est aussi présent une fois l'histoire terminée, on revient sur le dernier noeud d'action en cours plutôt qu'au tout début du pack.

Il pourrait etre interessant d'ajouter un paramètre a la ligne de commande afin de conserver les deux fonctionnements.

J'ajouterais également qu'un noeud final comme dans les packs officiels du genre "Tu veux écouter une nouvelle histoire ?" et pourquoi pas un choix supplementaire par exemple "Tu veux modifier cette histoire ?" si l'on souhaite également conserver le fonctionnement actuel

**Comment by jersou** [comment]
ok, c'est problématique quand le titre du menu est terminé. Le lien "home" de ces entrées de menus devraient pointer vers le mm noeud que le "home" du titre de menu.

Je fixer ça je pense, et en effet, ça devrait être le comportement de base, je ne pense pas qui soit nécessaire de faire une option pour permettre de garder le comportement actuel.

Je ne pense pas faire la deuxième proposition cela dit, car ça demande un peu de boulot, mais c'est une bonne idée. Ça pourrait être un "0-end.mp3" comme l'actuel "0-item.mp3" pour les titres de menu.

**Comment by jersou** [comment]
fix présent dans la dernière release  : https://github.com/jersou/studio-pack-generator/releases/tag/v0.2.2
