### ISSUE TITLE
Génération depuis RSS URL en erreur si nom avec caractères spéciaux

### ISSUE THREAD

**Issue by pl6025** [jersou/studio-pack-generator#2]
Bonjour,

Merci pour cet outil (bon je n'ai pas encore réussi à arriver à sortir un zip, mais je progresse :)).

En voulant générer automatiquement le pack pour les podcast Bestioles de France inter : https://www.franceinter.fr/emissions/bestioles (lien RSS : http://radiofrance-podcast.net/podcast09/rss_22046.xml), j'ai remarqué que TOUTES les histoires comportant un ":" dans le nom ne sont pas générées correctement.

Exemple : Lièvre : la hase de mars, j'ai un fichier "xxxx - Lièvre : la hase de mars " (où xxxx correspond à un numéro) et avec un espace final. Mais derrière, il n'y a pas de fichier MP3 de chargé et donc pas de conversion.
Par contre pour "Le requin blanc en a marre qu'on le traite de méchant !" cela fonctionne bien.

Je me dit qu'il faudrait peut-être remplacer certains caractères spéciaux des noms pour que cela fonctionne bien.

Faut-il d'autres informations pour aider à résoudre ce "problème" ? Si oui, quel type et comment les extraire ?

**Comment by pl6025** [comment]
Petite précision, je suis sur windows 10 et j'ai récupéré le zip vendredi 17/12 au soir.

**Comment by pl6025** [comment]
Désolé de "spammer", je viens de voir que la release "v0.1.10 / 2021.12.19" traitait peut-être ce problème : 
"fix(rss/windows): remove Windows forbidden characters :*?<>|" je pense que le commit 4fb51e1d4ed39bfac461dafe1cbf526e4df869de corrige bien cela (il y a l'air d'y avoir le ":" dans la liste des éléments traités).
Merci de clore mon "issue" si c'est bien traité avec la v01.1.10.
Et désolé de signaler quelque chose de déjà traité.

**Comment by jersou** [comment]
Bonjour, pas de problème ! le commit en question date d'hier à peine :-) 
Je clos l'issue qui a l'air de correspondre à ce commit en effet.
Pour info, ce flux a été également transformé en pack sur ce forum : https://www.dealabs.com/discussions/discussion-utilisation-de-studio-pour-lunii-1876791

Le forum liste les packs là (cf la première page) : https://docs.google.com/spreadsheets/d/1op31mqaXteREqKiEdhOWokp8DbWd2Qiqiu33DalxB-A/edit#gid=0
