### ISSUE TITLE
Utilisation d'un noeud de scène plutôt que le noeud départ

### ISSUE THREAD

**Issue by MrAlucardDante** [jersou/studio-pack-generator#20]
Le "Noeud départ" est maintenant déprécié et le Discord Lunii Créations préconise d'utiliser un "Noeud de scène" avec l'option "Noeud de départ" (`"squareOne":true` dans le story.json)

**Comment by malexxx** [comment]
❤️

**Comment by jersou** [comment]
Je ne comprends pas, ce n'est pas déjà le cas ?
https://github.com/jersou/studio-pack-generator/blob/main/test_data/pack/0-min/story.json#L41
C'est quoi le "Noeud départ" ? SPG ne fait que des `stageNodes` et `actionNodes`

**Comment by jersou** [comment]
c'est le `"type": "cover"` à convertir en `"type": "stage"`,` peut etre ?

**Comment by MrAlucardDante** [comment]
Surement. J’ai généré un pack cet après-midi avec la dernière version de SPG et c’est bien le « Noeud Depart » (bleu dans Studio) qui apparaît, plutot qu’un « Noeud de scène » (vert dans studio)

**Comment by jersou** [comment]
ok, ça semble être ça, je fais la modif

**Comment by jersou** [comment]
dispo dans la dernière release : https://github.com/jersou/studio-pack-generator/releases/tag/v0.2.3
