### ISSUE TITLE
metadata.json nightmode is not packaged correctly

### ISSUE THREAD

**Issue by lasconic** [jersou/studio-pack-generator#25]
* Extract a pack with nightmode
* Inspect the metadata.json and it should have : `nightModeAvailable : True`
* Repack with -miva
* Open in Studio

Expected result : the pack is display with night mode On
Actual result : the pack is displayed with night mode Off

I believe it's a typo between `nightModeAvailable` and `nightMode`
FWIW, I prefer `nightModeAvailable`

**Comment by jersou** [comment]
pour résumer le bug : dans les metadata.json on utilise "nightMode" mais l'outil d'extraction générait des metadata avec "nightModeAvailable"
