### ISSUE TITLE
Utiliser TTS système pour MacOS

### ISSUE THREAD

**Issue by dmaxime** [jersou/studio-pack-generator#3]
Bonjour, 

Un grand merci pour ce logiciel bien utile !
Sur MacOS, je n'ai pas réussi à générer les fichiers audio des menus (pas trouvé d'installation simple de picoTTS). Serait-il possible d'utiliser comme pour Windows le TTS du système MacOS ?
Via l'utilitaire 'say', par ex.
   say -v Thomas -o menu.wave "Ma belle histoire"

**Comment by jersou** [comment]
Bonjour, je peux faire cette modif oui, je vais voir ça d'ici à quelques jours, mais je ne pourrais pas tester, il faudra me confirmer que ça fonctionne.

**Comment by jersou** [comment]
Je viens de publier la v0.1.11 qui ajoute cette possibilité : si on est sous MacOS, et qu'on n'a pas pico2wave, alors le programme essaye "say", mais sans l'option "-v Thomas".
Mais je n'ai pas de MacOS, je ne peux pas tester ça. J'attends votre retour pour clore/corriger.

**Comment by dmaxime** [comment]
Merci, cela a fonctionné avec quelques ajustements ici #6
