### ISSUE TITLE
Part sorting is not human friendly

### ISSUE THREAD

**Issue by ggerbaud** [jersou/studio-pack-generator#7]
First of all I want to thank you for the great job here.

I just try this tool with a huge french Podcast "Encore une histoire" (I think you know as it is mentionned in the doc).
It has generate 17 parts but once on the Lunii, the part 10 follow immediately the part 1.
It's kind of obvious since "Partie 10" is before "Partie 2" in an alpha sort but it's not obvious for my sons and I understand them.

Can you find a trick to keep folder in a natural order and still generate accurate voice and image ?

I might take a look and submit a PR but I am not comfortable with JS.

**Comment by jersou** [comment]
Hello,
To fix this, you can rename files/folders like : https://github.com/jersou/studio-pack-generator#tips

> - The first digit of file/folder name are ignored, it's useful to sort stories/menus.
> - To keep numbers in generated items : "- 3 petits cochons.mp3" or "12 - 3 petits cochons.mp3".

**or you can use the new version v0.1.13 that fix this issue** : https://github.com/jersou/studio-pack-generator/releases
