### ISSUE TITLE
Feature : skip audio begining

### ISSUE THREAD

**Issue by GuillaumeFege** [jersou/studio-pack-generator#8]
Hello, thanks a lot for your great job.
Is it possible to add an option to do the following : 
Skip the start of the audio files 

That could be very usefull when I download podcasts with 30 or 40 second of advertisement.

Thanks.

**Comment by jersou** [comment]
Thank you for the contribution ! PR merged.

**Comment by jersou** [comment]
Available in the v0.1.17 : https://github.com/jersou/studio-pack-generator/releases/tag/v0.1.17

**Comment by jersou** [comment]
Si tu es français, je te conseille le discord : https://discord.com/channels/911349645752541244/911369446881390592 pour trouver plein de créations de packs par la communauté

**Comment by GuillaumeFege** [comment]
> Si tu es français, je te conseille le discord : https://discord.com/channels/911349645752541244/911369446881390592 pour trouver plein de créations de packs par la communauté

Merci, effectivement beaucoup de packs intéressant :-)
